### PR TITLE
Update vSphere from 3.1.0 to 3.1.1.

### PR DESCRIPTION
**Pull request by cluther**

### CODE REVIEW

**Comment by jplouis** [comment]
Is there an associated ticket? Waiting to hear back from L3 if this is going in 5.0.2 or 5.0.3.

**Comment by fraibacas** [comment]
https://jira.zenoss.com/browse/ZEN-17442
https://github.com/zenoss/zenoss-prodbin/pull/830

**Comment by jplouis** [comment]
@fraibacas so we want this for 5.0.2?

**Comment by fraibacas** [comment]
@jplouis Brett asked me to include it in 5.0.2 this morning

**Pull request merged**
